version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3014:3014"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4014:4014"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.docker
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env.docker
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
